Resources:
  
  ApiNode:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-07cc15c3ba6f8e287
      KeyName: PersonalTestKp
      SecurityGroups:
        - !Ref ApiSG
      UserData: !Base64 |
        #!/bin/bash
        sudo yum update -y
        sudo yum install -y docker
        sudo service docker start
        sudo usermod -aG docker ec2-user
  ApiSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh and web ports
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
  
  ApiDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: testdb
      Engine: mysql
      MasterUsername: root
      MasterUserPassword: abc123demodemo
      DBInstanceClass: db.t2.micro
      AllocatedStorage: '5'
      DBSecurityGroups:
        - !Ref DbSG
          
  DbSG:
    Type: AWS::RDS::DBSecurityGroup
    Properties:
      GroupDescription: SG for the database
      DBSecurityGroupIngress:
        - CIDRIP: 0.0.0.0/0
      
          
    
